name: life_sync
description: A new Flutter project.
publish_to: "none"

version: 1.1.0+3

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.1
  flutter_bloc: ^8.1.1
  go_router: ^13.0.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.5.0
  intro_slider: ^4.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # google_fonts: ^6.1.0
  flutter_svg: ^2.0.5
  table_calendar: ^3.0.9
  bottom_sheet: ^4.0.0
  fl_chart: ^0.66.2
  carousel_slider: ^4.2.1
  intl: ^0.18.1
  http: ^1.2.0
  cloud_firestore: ^4.14.0
  url_launcher: ^6.2.5
  google_sign_in: ^6.2.1
  # welltested: ^0.0.1

  # firebase_messaging: ^14.6.0
  # flutter_local_notifications: ^14.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  json_serializable: ^6.6.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  build_runner: ^2.3.3
  freezed: ^2.3.3
  hive_generator: ^2.0.0

# to run this use flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/app_icon/life_sync-01.png"
  # image_path_android: "assets/images/icon-710x599-android.png"
  # image_path_ios: "assets/images/icon-1024x1024.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  # adaptive_icon_background: "#9BCD8F" # only available for Android 8.0 devices and above
  # adaptive_icon_foreground: "assets/app_icon/LifeSync-01.png" # only available for Android 8.0 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  # background_color_ios: "#9BCD8F"

# # to run this use dart run flutter_native_splash:create
flutter_native_splash:
  image: assets/splash/LifeSync.png
  color: "#FFFFFF"

flutter:
  uses-material-design: true

  # Enables generation from arb files
  generate: true

  assets:
    - assets/icons/
    - assets/backgrounds/
    - assets/images/
    - assets/breathing_images/
    - assets/emotions/
    - assets/intro/
    - assets/socials/
    - assets/tests/
    - assets/shared_stories/
    - assets/menu_icons/
    - assets/fonts/Dosis/static/Dosis-Regular.ttf
    - assets/fonts/Poppins/Poppins-Regular.ttf
    - assets/fonts/Sansita/Sansita-Regular.ttf
    - assets/fonts/Signika/static/Signika-Regular.ttf
    - assets/fonts/Signika/static/Signika-Medium.ttf
    - assets/fonts/MedievalSharp/MedievalSharp-Regular.ttf

  # assets:
  #   -assets/notification_icon.png
